[package]
name = "chirm_encoding"
version = "0.1.0"
edition = "2024"

[dependencies]
opus = "0.3.0"

[dev-dependencies]
criterion = "0.7.0"
hound = "3.5.1"

[[bench]]
name = "benchmark"
harness = false
